package com.user.model;
// Generated 12.04.2021 20:56:30 by Hibernate Tools 4.3.1



/**
 * Dokument generated by hbm2java
 */
public class Dokument  implements java.io.Serializable {


     private Integer idDokument;
     private String title;
     private String past;

    public Dokument() {
    }

    public Dokument(String title, String past) {
       this.title = title;
       this.past = past;
    }
   
    public Integer getIdDokument() {
        return this.idDokument;
    }
    
    public void setIdDokument(Integer idDokument) {
        this.idDokument = idDokument;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPast() {
        return this.past;
    }
    
    public void setPast(String past) {
        this.past = past;
    }




}


