package com.user.model;
// Generated 12.04.2021 20:56:30 by Hibernate Tools 4.3.1



/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private int idEvent;
     private String titleOfCit;

    public Event() {
    }

	
    public Event(int idEvent) {
        this.idEvent = idEvent;
    }
    public Event(int idEvent, String titleOfCit) {
       this.idEvent = idEvent;
       this.titleOfCit = titleOfCit;
    }
   
    public int getIdEvent() {
        return this.idEvent;
    }
    
    public void setIdEvent(int idEvent) {
        this.idEvent = idEvent;
    }
    public String getTitleOfCit() {
        return this.titleOfCit;
    }
    
    public void setTitleOfCit(String titleOfCit) {
        this.titleOfCit = titleOfCit;
    }




}


