package com.user.model;
// Generated 12.04.2021 20:56:30 by Hibernate Tools 4.3.1



/**
 * Polzovatel generated by hbm2java
 */
public class Polzovatel  implements java.io.Serializable {


     private int idpolzovatel;
     private String name;
     private String nikname;
     private Integer vozrost;
     private String login;
     private String parol;

    public Polzovatel() {
    }

	
    public Polzovatel(int idpolzovatel) {
        this.idpolzovatel = idpolzovatel;
    }
    public Polzovatel(int idpolzovatel, String name, String nikname, Integer vozrost, String login, String parol) {
       this.idpolzovatel = idpolzovatel;
       this.name = name;
       this.nikname = nikname;
       this.vozrost = vozrost;
       this.login = login;
       this.parol = parol;
    }
   
    public int getIdpolzovatel() {
        return this.idpolzovatel;
    }
    
    public void setIdpolzovatel(int idpolzovatel) {
        this.idpolzovatel = idpolzovatel;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNikname() {
        return this.nikname;
    }
    
    public void setNikname(String nikname) {
        this.nikname = nikname;
    }
    public Integer getVozrost() {
        return this.vozrost;
    }
    
    public void setVozrost(Integer vozrost) {
        this.vozrost = vozrost;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getParol() {
        return this.parol;
    }
    
    public void setParol(String parol) {
        this.parol = parol;
    }




}


