package com.user.model;
// Generated 12.04.2021 20:56:30 by Hibernate Tools 4.3.1



/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private int idTeacher;
     private String fioTeachercol;
     private String category;
     private String dateOfCiti;

    public Teacher() {
    }

	
    public Teacher(int idTeacher) {
        this.idTeacher = idTeacher;
    }
    public Teacher(int idTeacher, String fioTeachercol, String category, String dateOfCiti) {
       this.idTeacher = idTeacher;
       this.fioTeachercol = fioTeachercol;
       this.category = category;
       this.dateOfCiti = dateOfCiti;
    }
   
    public int getIdTeacher() {
        return this.idTeacher;
    }
    
    public void setIdTeacher(int idTeacher) {
        this.idTeacher = idTeacher;
    }
    public String getFioTeachercol() {
        return this.fioTeachercol;
    }
    
    public void setFioTeachercol(String fioTeachercol) {
        this.fioTeachercol = fioTeachercol;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getDateOfCiti() {
        return this.dateOfCiti;
    }
    
    public void setDateOfCiti(String dateOfCiti) {
        this.dateOfCiti = dateOfCiti;
    }




}


